import { useEffect, useState } from "react";
import { useNavigate, useParams } from "react-router-dom";
import { ArrowLeft, Github, Globe, Handshake, Mail, MapPin } from "lucide-react";
import api from "../api/api";
import ProjectCard from "../components/ProjectCard";
import Button from "../components/ui/Button";
import { FullPageLoader } from "../components/ui/Spinner";
import { useToast } from "../components/ui/Toast";
import useAuth from "../hooks/useAuth";

function RequestModal({ title, children, onClose }) {
  return <div className="fixed inset-0 z-50 flex items-center justify-center bg-black/60 p-4"><div className="card w-full max-w-md p-6"><div className="mb-4 flex items-center justify-between"><h2 className="text-lg font-semibold text-ink">{title}</h2><button onClick={onClose} className="text-ink-muted hover:text-ink" aria-label="Close">×</button></div>{children}</div></div>;
}

export default function DeveloperProfile() {
  const { id } = useParams(); const navigate = useNavigate(); const toast = useToast(); const { user } = useAuth();
  const [data, setData] = useState(null); const [loading, setLoading] = useState(true); const [modal, setModal] = useState(null); const [message, setMessage] = useState(""); const [projectId, setProjectId] = useState(""); const [sending, setSending] = useState(false);
  useEffect(() => { api.get(`/auth/developers/${id}`).then((res) => { setData(res.data.data); setProjectId(String(res.data.data.projects.find((project) => project.status === "looking_for_collab")?.id || "")); }).catch(() => { toast.error("Developer not found."); navigate("/developers"); }).finally(() => setLoading(false)); }, [id, navigate, toast]);
  if (loading) return <FullPageLoader label="Loading developer profile…" />;
  if (!data) return null;
  const { developer, projects } = data; const isSelf = Number(id) === user?.id;
  const send = async (event) => { event.preventDefault(); if (!message.trim()) return; setSending(true); try { if (modal === "contact") await api.post(`/auth/developers/${id}/contact`, { message: message.trim() }); else { if (!projectId) { toast.error("This developer has no projects open for collaboration."); return; } await api.post(`/projects/${projectId}/collab`, { message: message.trim() }); } toast.success(modal === "contact" ? "Contact request sent." : "Collaboration request sent."); setModal(null); setMessage(""); } catch (error) { toast.error(error.response?.data?.message || "Unable to send request."); } finally { setSending(false); } };
  const collabProjects = projects.filter((project) => project.status === "looking_for_collab");
  return <div className="mx-auto max-w-5xl"><Button variant="ghost" size="sm" className="mb-6 -ml-2" onClick={() => navigate(-1)}><ArrowLeft className="h-4 w-4" /> Back to developers</Button><section className="card mb-8 p-6"><div className="flex flex-col justify-between gap-5 sm:flex-row"><div className="flex gap-4"><span className="flex h-16 w-16 shrink-0 items-center justify-center rounded-2xl bg-gradient-to-br from-brand to-brand-deep text-2xl font-semibold text-white">{developer.name?.charAt(0)?.toUpperCase() || "D"}</span><div><h1 className="text-2xl font-semibold text-ink">{developer.name}</h1>{developer.bio && <p className="mt-2 max-w-2xl text-ink-soft">{developer.bio}</p>}<div className="mt-3 flex flex-wrap gap-3 text-sm text-ink-muted">{developer.location && <span className="inline-flex items-center gap-1"><MapPin className="h-4 w-4" />{developer.location}</span>}{developer.github_username && <a href={`https://github.com/${developer.github_username}`} target="_blank" rel="noreferrer" className="inline-flex items-center gap-1 hover:text-brand-soft"><Github className="h-4 w-4" />GitHub</a>}{developer.website && <a href={developer.website} target="_blank" rel="noreferrer" className="inline-flex items-center gap-1 hover:text-brand-soft"><Globe className="h-4 w-4" />Website</a>}</div></div></div>{!isSelf && <div className="flex h-fit flex-wrap gap-2"><Button variant="secondary" onClick={() => setModal("contact")}><Mail className="h-4 w-4" /> Ask for contact</Button><Button onClick={() => setModal("collab")} disabled={!collabProjects.length}><Handshake className="h-4 w-4" /> Collaborate</Button></div>}</div></section><h2 className="mb-4 text-xl font-semibold text-ink">Projects by {developer.name}</h2>{projects.length ? <div className="space-y-4">{projects.map((project) => <ProjectCard key={project.id} project={{ ...project, owner_name: developer.name }} />)}</div> : <p className="text-sm text-ink-muted">No projects shared yet.</p>}
    {modal && <RequestModal title={modal === "contact" ? `Contact ${developer.name}` : `Collaborate with ${developer.name}`} onClose={() => setModal(null)}><form onSubmit={send} className="space-y-4">{modal === "collab" && <div><label className="field-label">Project</label><select className="field" value={projectId} onChange={(event) => setProjectId(event.target.value)} required>{collabProjects.map((project) => <option key={project.id} value={project.id}>{project.title}</option>)}</select></div>}<div><label className="field-label">Message</label><textarea className="field min-h-28 resize-y" value={message} onChange={(event) => setMessage(event.target.value)} placeholder="Introduce yourself and explain what you would like to discuss…" required /></div><div className="flex justify-end gap-3"><Button type="button" variant="secondary" onClick={() => setModal(null)}>Cancel</Button><Button type="submit" loading={sending}>Send request</Button></div></form></RequestModal>}
  </div>;
}
